name: Deploy mdBook to GitHub Pages

on:
  push:
    branches:
      - feature/setup
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
       contents: write
    steps:
    - uses: actions/checkout@v2

    - name: Setup mdbook
      uses: peaceiris/actions-mdbook@v2
      with:
        mdbook-version: 'latest'

    - run: |
        cd praesentation
        mdbook build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./presentation/book
